networks:
  dev:

services:
  nginx:
    image: nginx
    ports:
      - '8085:80'
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - backend
      - frontend
    networks:
      - dev
  frontend:
    build:
      context: ./Frontend
    networks:
      - dev
  backend:
    build:
      context: ./Backend
    networks:
      - dev
